spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pin4u_be
    username: ${DB_USER:pin4u} # pin4u_be에서 작업
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update    # 엔티티 변경 자동 반영(편하게 개발)
    show-sql: true
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: false #초기 개발 동안 마이그레잇녀 비활성화
    baseline-on-migrate: true

app:
  seed:
    enabled: true       # 로컬에서만 시드 실행
  kakao:
    enabled: false      # 6단계에서 ON
  og:
    image-enabled: false
  ratelimit:
    enabled: false

kakao:
  api:
    base-url: https://dapi.kakao.com
    key: ${KAKAO_REST_API_KEY:}
